app <- ShinyDriver$new("../")
app$snapshotInit("test-1")

app$setInputs(obs = 11)
app$setInputs(obs = 13)
app$setInputs(obs = 14)
app$setInputs(obs = 15)
app$snapshot()
app$setInputs(dataset = "pressure")
app$setInputs(update = "click")
app$snapshot()
app$setInputs(obs = 14)
app$setInputs(obs = 11)
app$setInputs(obs = 10)
app$snapshot()
app$setInputs(update = "click")
app$snapshot()
